problemx = problem30

build:
	@mkdir -p bin
	@gcc -Wall -Wextra -O3 -o bin/${problemx} main.c -lm
	@echo 'Finished compiling'
	@echo 'Execute with `./bin/${problemx}`'

clean:
	@rm -rf bin
	@echo 'bin/ deleted'
